version: '3.8'

services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      - POSTGRES_USER=iotdesk
      - POSTGRES_PASSWORD=iotdesk
    ports:
      - 5432:5432
    volumes:
    - /postgresql:/var/lib/postgreslq/data